# Generated by Django 4.1.3 on 2023-09-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('answer1', models.IntegerField()),
                ('answer2', models.IntegerField()),
                ('answer3', models.IntegerField()),
                ('answer4', models.IntegerField()),
                ('answer5', models.IntegerField()),
                ('answer6', models.IntegerField()),
                ('answer7', models.IntegerField()),
                ('answer8', models.IntegerField()),
                ('answer9', models.IntegerField()),
                ('answer10', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
