# Generated by Django 4.1.3 on 2023-09-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='lname',
        ),
    ]
