# Generated by Django 4.1.3 on 2023-09-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detail',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
