# Generated by Django 4.1.3 on 2023-09-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_answer_id_alter_detail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='username',
        ),
        migrations.DeleteModel(
            name='question',
        ),
        migrations.DeleteModel(
            name='answer',
        ),
        migrations.DeleteModel(
            name='detail',
        ),
    ]
