# Generated by Django 4.1.3 on 2023-09-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detail',
        ),
    ]
