# Generated by Django 4.1.3 on 2023-09-17 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0016_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer1', models.IntegerField()),
                ('answer2', models.IntegerField()),
                ('answer3', models.IntegerField()),
                ('answer4', models.IntegerField()),
                ('answer5', models.IntegerField()),
                ('answer6', models.IntegerField()),
                ('answer7', models.IntegerField()),
                ('answer8', models.IntegerField()),
                ('answer9', models.IntegerField()),
                ('answer10', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
