# Generated by Django 4.1.3 on 2023-09-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question',
        ),
    ]
