# Generated by Django 4.1.3 on 2023-09-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
